postgres:
  image: postgres:9.3

redis:
  image: redis:2.6

# Uncomment the below lines to run selenium tests locally. Don't forget the
# line in the `web` section below too.
#
#selenium:
#  build: ./docker-compose/seleniumff
#  ports:
#    - "5900:5900"

kinesis:
  build: ./docker-compose/kinesalite
  command: "--path /var/lib/kinesalite"
  volumes:
    - "./tmp/cache:/var/lib/kinesalite"
  ports:
    - "4567:4567"
  environment:
    VIRTUAL_HOST: kinesis.docker
    VIRTUAL_PORT: 4567

web:
  build: ./docker-compose
  command: bundle exec bin/rails s
  ports:
    - "3000:3000"
  volumes:
    - ".:/app"
  links:
    - postgres
    - redis
#    - selenium
    - kinesis
  environment:
    RACK_ENV: development
    VIRTUAL_HOST: .canvas.docker

jobs:
  build: ./docker-compose
  command: bundle exec script/delayed_job run
  volumes:
    - ".:/app"
  links:
    - postgres
    - redis
    - kinesis
  environment:
    RACK_ENV: development

guard:
  build: ./docker-compose
  command: bundle exec guard -i
  ports:
    - "4000:4000"
  volumes:
    - ".:/app"
  environment:
    RACK_ENV: development
