version: "2.3"
services:
  karma:
    environment:
      - JSPEC_GROUP
    build:
      context: .
      dockerfile: ./build/new-jenkins/js/Dockerfile-karma
      args:
        PATCHSET_TAG: $PATCHSET_TAG
    init: true
