# See doc/docker/README.md or https://github.com/instructure/canvas-lms/tree/master/doc/docker
version: '2'
services:
  web: &WEB
    build:
      context: .
    links:
      - postgres
      - redis

  jobs:
    <<: *WEB
    command: bundle exec script/delayed_job run

  postgres:
    build: ./docker-compose/postgres

  redis:
    image: redis:alpine
