version: "2.3"
services:
  canvas:
    environment:
      - JSPEC_GROUP
    image: local/js-runner
    build:
      context: .
      dockerfile: ./build/new-jenkins/js/Dockerfile
      args:
        PATCHSET_TAG: $PATCHSET_TAG
        WEBPACK_BUILDER_TAG: $WEBPACK_BUILDER_TAG
    init: true
