test:
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  shard_name: public
  schema_search_path: "''"
  use_qualified_names: true
  database: canvas_test_rails
  shard1: canvas_test_shard_1
  shard2: canvas_test_shard_2
  test_shard_1: canvas_test_shard_1
  test_shard_2: canvas_test_shard_2
