# to use this add docker-compose/consul.override.yml
# to your COMPOSE_FILE var in .env

version: '2'
services:
  web:
    links:
      - consul

  consul:
    image: consul:0.7.2
    command: agent -dev -client 0.0.0.0 -datacenter canvas-dev -node canvas-consul -bootstrap
    environment:
      GOMAXPROCS: "2"
      VIRTUAL_PORT: 8500
