# to use this add docker-compose/selenium.override.yml
# to your COMPOSE_FILE var in .env

version: '2'
services:
  selenium-firefox:
    build: ./docker-compose/selenium-firefox
    ports:
      - 5900:5900
    environment:
      VIRTUAL_HOST: seleniumff.docker
      remote_url: http://seleniumff.docker/wd/hub
      browser: firefox

  selenium-chrome:
    build: ./docker-compose/selenium-chrome
    ports:
      - 5901:5900
    environment:
      VIRTUAL_HOST: seleniumch.docker
      remote_url: http://seleniumch.docker/wd/hub
      browser: chrome
