# this config file is useful if you don't want to run a consul
# cluster with canvas.  Just provide the config data you would
# like for the DynamicSettings class to find, and it will use
# it whenever a call for consul data is issued. Data should be
# shaped like the example below, one key for the related set of data,
# and a hash of key/value pairs (no nesting)
development:
  address-book:
    app-host: "http://address-book.docker"
    secret: "opensesame"
  live-events-subscription-service:
    app-host: "http://les.docker"
    sad-panda: null
  rich-content-service:
    app-host: "rce.docker"
  canvas:
    encryption-secret: "astringthatisactually32byteslong"
    signing-secret: "astringthatisactually32byteslong"
  live-events:
    aws_endpoint: http://kinesis.canvaslms.docker
    kinesis_stream_name: live-events
  math-man:
    base_url: 'http://mathman.docker'
    use_for_svg: 'false'
    use_for_mml: 'false'
