font_name: canvas-icons
preprocessor_path: false
autowidth: false
no_hash: true
force: false
debug: false
quiet: false
input:
  vectors: public/fonts/icons
  templates: public/fonts/icons
output:
  fonts: public/fonts/canvas
  css: app/stylesheets/components
templates: 
  - _canvas-icons.scss