Datafixup/EagerLoad: &Datafixup
  Enabled: true
  Include:
    - "**/db/migrate/*.rb"
    - "**/lib/data_fixup/*.rb"

Datafixup/FindIds:
  <<: *Datafixup

Lint/FreezeConstants:
  Enabled: true

Lint/NoFileUtilsRmRf:
  Enabled: true

Lint/NoSleep:
  Enabled: true

Migration/ConcurrentIndex: &Migration
  Enabled: true
  Include:
    - "**/db/migrate/*.rb"

Migration/PrimaryKey:
  <<: *Migration

Migration/RemoveColumn:
  <<: *Migration

Migration/SendLater:
  <<: *Migration

Rails/SmartTimeZone:
  Enabled: true

Specs/EnsureSpecExtension: &Specs
  Enabled: true
  Include:
    - "**/spec/**/*.rb"
    - "**/spec_canvas/**/*.rb"

Specs/NoBeforeAll:
  <<: *Specs

Specs/NoBeforeOnceStubs:
  <<: *Specs

Specs/NoExecuteScript:
  <<: *Specs

Specs/PreferFOverFj:
  <<: *Specs

Specs/ScopeHelperModules:
  <<: *Specs
