Datafixup/EagerLoad: &Datafixup
  Enabled: true
  Include:
    - "**/db/migrate/*.rb"
    - "**/lib/data_fixup/*.rb"

Lint/FreezeConstants:
  Enabled: true

Lint/NoFileUtilsRmRf:
  Enabled: true

Lint/NoSleep:
  Enabled: true
  Exclude:
    - "**/spec/selenium/test_setup/**/*.rb"

Migration/ConcurrentIndex: &Migration
  Enabled: true
  Include:
    - "**/db/migrate/*.rb"

Migration/ModelBehavior:
  Enabled: true
  Include:
    - "**/db/migrate/*.rb"
    - "lib/data_fixup/*.rb"
  Whitelist:
    - Canvas
    - DataFixup
    - Switchman
    - Shard
    - Account.default
    - Account.site_admin
    - "*.quoted_table_name"
    - "*.connection"
    - "*.transaction"
    - "*.find_ids_in_batches"
    - "*.find_ids_in_ranges"
    - "*.update_all"
    - "*.delete_all"
    - "ActiveRecord::Migration"

Migration/PrimaryKey:
  <<: *Migration

Migration/RemoveColumn:
  <<: *Migration

Migration/SendLater:
  <<: *Migration

Rails/SmartTimeZone:
  Enabled: true

Specs/EnsureSpecExtension: &Specs
  Enabled: true
  Include:
    - "**/spec/**/*.rb"
    - "**/spec_canvas/**/*.rb"

Specs/NoBeforeAll:
  <<: *Specs

Specs/NoBeforeOnceStubs:
  <<: *Specs

Specs/NoExecuteScript:
  <<: *Specs
  Exclude:
    - "**/spec/selenium/test_setup/**/*.rb"

Specs/PreferFOverFj:
  <<: *Specs

Specs/ScopeHelperModules:
  <<: *Specs
