---
new_post_policy_icons:
  state: hidden
  display_name: New Post Policy Icons
  description: Updates the display of Post Policy icons in the New Gradebook
    assignment column header.
  applies_to: RootAccount
gradebook_reserved_importer_bugfix:
  state: hidden
  display_name: Gradebook Import Reserved Names Bugfix (APG-122)
  description: Behaviour change related to the bugfix in APG-122. Do not allow custom columns to be created that
    are titled the same as gradebook importer reserved names, also ignore non-active custom columns on gradebook
    import as well as those that use reserved names.
  applies_to: SiteAdmin
add_grading_scheme_to_admin_grade_reports:
  state: hidden
  display_name: Add Grading Scheme to Admin Grade Reports
  description: Includes grade values in the admin grade reports.
  applies_to: RootAccount
allow_postable_submission_comments:
  state: hidden
  display_name: Allow Postable Submission Comments
  description: For manually posted assignments, the presence of a submission comment not by the submission's own
    user will allow posting the assignment. Previously, this would have required a grade before posting could
    occur.
  applies_to: RootAccount
analytics2_api_access:
  state: hidden
  applies_to: RootAccount
  display_name: New Analytics API Access
  description: Enables new API endpoints for the course and user data provided by New Analytics.
gradebook_export_sort_order_bugfix:
  state: hidden
  applies_to: SiteAdmin
  display_name: Gradebook Export Sort Order Bugfix (Tally-219)
  description: Changes the sort order of the gradebook export to more closely match the canvas documentation
include_speed_grader_in_assignment_header_menu:
  state: hidden
  applies_to: SiteAdmin
  display_name: Include SpeedGrader in Assignment Header Menu
  description: Includes a link to SpeedGrader in the assignment header menu in Gradebook.
prefetch_gradebook_user_ids:
  state: hidden
  applies_to: SiteAdmin
  display_name: Prefetch User IDs in Gradebook
  description: Load user ids upon page load so that Gradebook loads more quickly.
datadog_rum_js:
  state: hidden
  applies_to: SiteAdmin
  display_name: Datadog RUM JS Agent
  description: Include the Datadog RUM JS Agent in the document HEAD.
grade_calculator_performance_improvements:
  state: hidden
  applies_to: SiteAdmin
  display_name: Grade Calculator Performance Improvements
  description: Performance improvements for the grade calculation process.
gradebook_dataloader_improvements:
  state: hidden
  applies_to: SiteAdmin
  display_name: Gradebook Data Loading Performance Improvements
  description: Performance improvements for loading data into Gradebook.
  environments:
    ci:
      state: on
    development:
      state: on
    test:
      state: on
missing_policy_applicator_emits_live_events:
  state: hidden
  applies_to: RootAccount
  display_name: Missing Policy Applicator Emits Live Events
  description: Allows the missing policy applicator to emit submission_updated live events for each submission
    marked as missing.
disable_post_to_sis_when_grading_period_closed:
  state: hidden
  applies_to: RootAccount
  display_name: Disable Post to SIS for Assignment in Closed Grading Periods
  description: If set, turns off post-to-SIS functionality for assignments when their grading period closes.
    Only applies if the "Enable new SIS integration settings" feature is enabled.
final_grade_override_in_gradebook_history:
  state: hidden
  applies_to: SiteAdmin
  display_name: Final Grade Override in Gradebook History
  description: Includes overridden course grades in the Gradebook History.
  applies_to: RootAccount
responsive_student_grades_page:
  state: hidden
  applies_to: RootAccount
  display_name: Responsive Student Grades Page
  description: Makes the student grades page responsive.
