rce_auto_save:
  state: hidden
  display_name: RCE Auto-Save
  description: |-
    If RCE Enhancements are also enabled,
    the RCE will auto-save your work as you go
  applies_to: Course
  root_opt_in: true
cc_in_rce_video_tray:
  state: hidden
  display_name: Edit Closed Captions
  description: Edit closed captions/subtitles to videos from the video options tray in the RCE
  applies_to: SiteAdmin
rce_lti_favorites:
  state: hidden
  display_name: Support favorite LTI tools in the RCE
  description: Let the site administrator select up to 2 LTI apps as favorites, which will then be displayed in the RCE's toolbar
  applies_to: SiteAdmin
