---
outcome_alignment_non_scoring_content:
  state: hidden
  applies_to: RootAccount
  display_name: Outcome alignment to non-scoring content
  description: |-
    Allows aligning outcomes to non-scoring content
  environments:
    production:
      state: disabled
outcome_guid_course_exports:
  state: hidden
  applies_to: RootAccount
  display_name: "Reduce outcome duplication on course import"
  description: "Ensures that outcomes that have already been imported
    into a course are not duplicated if they are imported again"
selectable_outcomes_in_course_copy:
  state: hidden
  applies_to: RootAccount
  display_name: "Selectable outcomes during course content migration"
  description: "Allows learning outcomes to be selectable when migrating course content"
limit_section_visibility_in_lmgb:
  state: hidden
  applies_to: RootAccount
  display_name: Restricted view for teachers in LMGB
  description: Hides certain students and sections in the LMGB if the teacher only
    has access to a particular section
outcome_alignments_course_migration:
  state: hidden
  applies_to: RootAccount
  display_name: Outcomes Service Alignment Migration
  description: Includes Outcomes Service alignments when exporting and importing
    course content
bulk_delete_pages:
  state: hidden
  applies_to: RootAccount
  display_name: Page Bulk Deleting
  description: Allow pages to be deleted in bulk
account_level_mastery_scales:
  state: hidden
  applies_to: RootAccount
  display_name: Account-level Mastery Scales
  description: Allows Account-level mastery scales and proficiency calculations,
    replacing per-outcome scales
