---
outcome_alignment_non_scoring_content:
  state: hidden
  applies_to: RootAccount
  display_name: Outcome alignment to non-scoring content
  description: |-
    Allows aligning outcomes to non-scoring content
rubrics_in_course_navigation:
  state: hidden
  applies_to: RootAccount
  display_name: Rubrics in course navigation
  description: |-
    Includes rubrics in the course sidebar navigation
  touch_context: true
decouple_rubrics:
  state: hidden
  applies_to: RootAccount
  display_name: "Modify permissions for Account Rubrics"
  description: "Change Rubrics visibility on Accounts to depend on the Rubrics permission
    instead of the Learning Outcomes permission"
import_outcomes_permission_fix:
  state: hidden
  applies_to: RootAccount
  display_name: "Hide the Import Learning Outcomes button based on user permissions"
  description: "Ensures that users without the Import Outcomes permission cannot see
    the button within the Outcomes tab"
outcome_guid_course_exports:
  state: hidden
  applies_to: RootAccount
  display_name: "Reduce outcome duplication on course import"
  description: "Ensures that outcomes that have already been imported
    into a course are not duplicated if they are imported again"
selectable_outcomes_in_course_copy:
  state: hidden
  applies_to: RootAccount
  display_name: "Selectable outcomes during course content migration"
  description: "Allows learning outcomes to be selectable when migrating course content"
limit_section_visibility_in_lmgb:
  state: hidden
  applies_to: RootAccount
  display_name: Restricted view for teachers in LMGB
  description: Hides certain students and sections in the LMGB if the teacher only
    has access to a particular section
outcome_alignments_course_migration:
  state: hidden
  applies_to: RootAccount
  display_name: Outcomes Service Alignment Migration
  description: Includes Outcomes Service alignments when exporting and importing
    course content
