---
confetti_for_assignments:
  state: hidden
  display_name: Confetti for On-Time Submissions
  description: |-
    Displays confetti for users that turn in an assignment prior
    to the set due date.
  applies_to: RootAccount

confetti_for_valid_links:
  state: hidden
  display_name: Confetti for valid links
  description: |-
    Displays confetti for teachers that run the link validator on
    a course and no issues are found.
  applies_to: RootAccount

deprecate_sms:
  state: hidden
  display_name: Restrict SMS to Select Types
  description: |-
    Disables SMS notifications for all types except announcements and
    grade changes.
  applies_to: SiteAdmin

hide_course_sections_from_students:
  state: hidden
  display_name: Hide Course Sections from Students
  description: |-
    Allows teachers to hide course sections from students on the People page when there is more than one section in the course.
  applies_to: RootAccount

notification_update_account_ui:
  state: hidden
  display_name: Account level notification preferences UI update
  description: |-
    Updates account notification preferences UI to be a more current
    and updated user experience
  applies_to: SiteAdmin

past_announcements:
  state: hidden
  display_name: Show past account level announcements to users
  description: |-
    Show past account level announcements to users. Allows
    a user to view announcemnts that have ended or been dismissed.
  applies_to: RootAccount

react_announcement_discussion_edit:
  state: hidden
  display_name: Update announcement/discussion edit page to use react/instui
  description: |-
    This refactor will make this page more maintainable and easily
    allow us to make the page more accessible
  applies_to: RootAccount

react_inbox:
  state: hidden
  display_name: Update Inbox page to use react/instui
  description: |-
    This refactor will make this page more maintainable
  applies_to: RootAccount

reduce_push_notifications:
  state: hidden
  display_name: Restrict Push Notifications to Select Types
  description: |-
    Disables Push notifications for certain types.
  applies_to: SiteAdmin

smart_alerts:
  state: hidden
  display_name: Smart alerts
  description: |-
    Notify students in time of assignments that require their attention.
  applies_to: RootAccount

trophy_case:
  state: hidden
  display_name: Trophy case
  description: |-
    Display historical view of achievements of users
  applies_to: SiteAdmin
